# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vkusnoitochkapay.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_coordwidget(object):
    def setupUi(self, coordwidget):
        coordwidget.setObjectName("coordwidget")
        coordwidget.resize(745, 144)
        coordwidget.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(coordwidget)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 541, 64))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(29, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Pricee = QtWidgets.QLabel(self.groupBox)
        self.Pricee.setObjectName("Pricee")
        self.horizontalLayout.addWidget(self.Pricee)
        coordwidget.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(coordwidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 21))
        self.menubar.setObjectName("menubar")
        coordwidget.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(coordwidget)
        self.statusbar.setObjectName("statusbar")
        coordwidget.setStatusBar(self.statusbar)

        self.retranslateUi(coordwidget)
        QtCore.QMetaObject.connectSlotsByName(coordwidget)

    def retranslateUi(self, coordwidget):
        _translate = QtCore.QCoreApplication.translate
        coordwidget.setWindowTitle(_translate("coordwidget", "MainWindow"))
        self.groupBox.setTitle(_translate("coordwidget", "GroupBox"))
        self.label.setText(_translate("coordwidget", "Name of the food what you choose"))
        self.Pricee.setText(_translate("coordwidget", "Price"))
